### ISSUE TITLE
插件很好用,但是如何对插件文件进行分类?搜索?

### ISSUE THREAD

**Issue by raymond8825** [suka233/siyuan-kmind-plugin#1]
插件很好用,但是在使用上还是有以下几个问题:
1. 如何对插件文件进行分类?所有的插件都堆在一个插件栏里感觉不太好管理
2. 联动不错,但是如何搜索kmind记录的内容呢?
<img width="382" alt="image" src="https://github.com/suka233/siyuan-kmind-plugin/assets/41637672/d0e301e1-c640-4953-a5cd-6fcaecb2f1f3">

3. 实际上iframe倒是有一个好处就是各个终端随便看,而不用考虑是否支持插件,比如手机端就可以查看iframe的kmind,但是不支持插件

**Comment by suka233** [comment]
1.分类问题我也在考虑如何会更好一点，如果是文件夹式的管理的话，符合操作直觉，但是每次刷新目录都需要递归遍历文件夹，如果文件夹多了的话，可能会有性能影响。所以我更倾向于使用标签管理，每个导图可以自定义标签，dock栏可以根据标签来筛选导图
2.搜索的话，插件和挂件需要分开讨论：
    对于插件：如果只是单张kmind内部节点文本的搜索，是可以搞定的。甚至搜索所有导图文件的节点，也可以做到。但是如果要让思源的搜索能搜索到kmind内部的节点的话，目前来看比较难办到，因为kmind的数据实际上是和思源的数据隔离的，除非d大提供接口，让我可以把kmind内部的节点数据暴露给思源，那么应该就可以做到思源自带的搜索来搜索节点内容了。
    对于挂件：我目前的想法是，把节点的文本内容放到挂件块的属性上，这样思源就能搜索到了
3.我也同意iframe的好处，其中一个就是隔离样式。因为做插件的时候，很多kmind的样式会影响到思源的全局样式，所以修改了蛮多的，并且，插件kmind的全屏功能也不如挂件好搞，所以挂件有全屏功能，而插件暂时没有

**Comment by raymond8825** [comment]
确实是这样,大佬想的周到,期待大佬完善更多的功能

**Comment by winter60** [comment]
> 所以我更倾向于使用标签管理，每个导图可以自定义标签 

标签也挺赞的，前提是多标签

**Comment by suka233** [comment]
请更新最新版本，已经可以在思源文档树新建KMind了，标签也是可以打的，跟思源普通文档使用方式一致

**Comment by vector090** [comment]
搜索功能很需要，能短平快实现功能就好

>  2.搜索的话，插件和挂件需要分开讨论： 对于插件：如果只是单张kmind内部节点文本的搜索，是可以搞定的。甚至搜索所有导图文件的节点，也可以做到。但是如果要让思源的搜索能搜索到kmind内部的节点的话，目前来看比较难办到，因为kmind的数据实际上是和思源的数据隔离的，除非d大提供接口，让我可以把kmind内部的节点数据暴露给思源，那么应该就可以做到思源自带的搜索来搜索节点内容了。 对于挂件：我目前的想法是，把节点的文本内容放到挂件块的属性上，这样思源就能搜索到了
