### ISSUE TITLE
思源笔记不是最大化的时候 界面会有问题

### ISSUE THREAD

**Issue by lsb226** [suka233/siyuan-kmind-plugin#11]
![image](https://github.com/suka233/siyuan-kmind-plugin/assets/16093704/b86f757e-cd6a-411c-b5cb-80069b77979b)

**Comment by suka233** [comment]
目前可以 右键导图，选择禅模式隐藏掉按钮来作为暂时解决方案

后面会尝试把上方操作栏作超出部分滚动查看的处理

**Comment by suka233** [comment]
已经修复~请升级插件和挂件都更新到最新版本即可
