### ISSUE TITLE
目前复制出来都是json数据，可否提供一个复制为大纲结构的能力

### ISSUE THREAD

**Issue by Chellane** [suka233/siyuan-kmind-plugin#12]

**Comment by suka233** [comment]
没有太懂你的需求的意思呢，请详细描述一下

**Comment by Chellane** [comment]
> 没有太懂你的需求的意思呢，请详细描述一下

比如，我选中某个节点，然后复制这个节点，在文本编辑器中粘贴后得到的是这个节点及下面节点的对象，期望像xmind那样，复制出来是个大纲结构

**Comment by suka233** [comment]
> > 没有太懂你的需求的意思呢，请详细描述一下
> 
> 比如，我选中某个节点，然后复制这个节点，在文本编辑器中粘贴后得到的是这个节点及下面节点的对象，期望像xmind那样，复制出来是个大纲结构

了解了，先记录下这个需求了，感谢提议

**Comment by suka233** [comment]
新版已添加
https://github.com/suka233/siyuan-kmind-plugin/releases/tag/v2.0.0-beta.1
