### ISSUE TITLE
无法删除创建的思维导图

### ISSUE THREAD

**Issue by lvvlxu** [suka233/siyuan-kmind-plugin#14]
v1.1.3
![image](https://github.com/suka233/siyuan-kmind-plugin/assets/44394483/5dbc4636-abfb-4571-841e-4eb6a23fc26d)

**Comment by suka233** [comment]
你好  请升级思源版本到v2.10.10 即可解决该问题
或者使用思源v2.10.8以及之前的版本

**Comment by lvvlxu** [comment]
好的，问题已解决，谢谢
