### ISSUE TITLE
插件模式下，请问可以支持创建文件夹吗，不同文件夹下面再创建思维导图

### ISSUE THREAD

**Issue by a877429929** [suka233/siyuan-kmind-plugin#17]
![image](https://github.com/suka233/siyuan-kmind-plugin/assets/73450291/3c74ec47-30a6-47d0-aa7a-3da3f7d3bde9)

**Comment by suka233** [comment]
暂时不支持奥

**Comment by winter60** [comment]
如果后续要支持，个人觉得无限层级的树状结构更合适

**Comment by suka233** [comment]
请更新最新版本，已经可以在思源文档树新建KMind了
