### ISSUE TITLE
建议增加一个全屏查看的按钮

### ISSUE THREAD

**Issue by jiaoting** [suka233/siyuan-kmind-plugin#18]
目前电脑上可以右键全屏，但是在ipad和手机端，由于不方便右键，全屏查看导图会非常不方便，建议在缩小放大那里有一个全屏按钮（禅模式也可以在这里设置一个按钮）

**Comment by jiaoting** [comment]
另外，建议使用右键拖动图布，左键拖动经常会误触节点

**Comment by suka233** [comment]
新版已添加
https://github.com/suka233/siyuan-kmind-plugin/releases/tag/v2.0.0-beta.1

**Comment by jiaoting** [comment]
没上商店？？

**Comment by suka233** [comment]
> 没上商店？？

上了 等思源拉取我的仓库就行 估计一个小时吧
具体进度查看这里：https://github.com/siyuan-note/bazaar/actions

**Comment by jiaoting** [comment]
挂件现在是跟这个一致的吗？我看挂件最近没更新呢

**Comment by suka233** [comment]
> 挂件现在是跟这个一致的吗？我看挂件最近没更新呢

这个版本的插件和挂件暂时不一致，之后会保持一致，原因如下：
新版插件的重要改动是跟挂件解耦，无需下载挂件就能使用插件了，然后现在挂件的话由于存储数据还有点问题，处理完毕了会更新挂件的
