### ISSUE TITLE
重新加载导图后，有些节点的图片会以最小的矩形进行展示

### ISSUE THREAD

**Issue by primejava** [suka233/siyuan-kmind-plugin#22]
关闭思源再打开，重新加载导图后，有些节点的图片会以最小的矩形进行展示，而不是之前已经设置好并保存了的矩形大小

**Comment by primejava** [comment]
从节点富文本输入窗口中添加的图片会有这种问题，直接点击图片按钮添加的图片不存在此问题

**Comment by suka233** [comment]
你好 这个问题在挂件的说明中有提及 是已知缺陷 暂时找不到比较好的方式解决 
请使用添加图片按钮的方式添加图片，或者直接激活节点，然后直接粘贴图片，这两种方式都不会出问题。
![image](https://github.com/suka233/siyuan-kmind-plugin/assets/43712875/144eb850-a18d-40b8-802a-07ef6f54a2a1)
