### ISSUE TITLE
你好，建议在节点样式上添加一个恢复默认样式按钮

### ISSUE THREAD

**Issue by QQQOrange** [suka233/siyuan-kmind-plugin#25]
如果多个节点设置了样式之后，想要恢复默认样式的话，目前是没有任何办法的，希望能够添加一个能够恢复默认样式的按钮

恢复默认样式的功能主要在于适应不同主题的需要，例如不小心把字体设成了黑色，那么换了别的主题背景是黑的，字也是黑的，就会看不清，但是默认样式就会自动改变字体的颜色

**Comment by suka233** [comment]
新版已添加
https://github.com/suka233/siyuan-kmind-plugin/releases/tag/v2.0.0-beta.1
