### ISSUE TITLE
可以增加孤立点吗

### ISSUE THREAD

**Issue by Allxy5** [suka233/siyuan-kmind-plugin#27]
或者可以增加多个中心
或者节点结构可以自由调整

现在的结构样式实用过程中老感觉达不到理想的结构效果

**Comment by Allxy5** [comment]
或者可以自己设计定义结构模板这样

**Comment by suka233** [comment]
抱歉  多个根节点暂时不支持

**Comment by Allxy5** [comment]
那可以增加自定义导图结构的功能吗

**Comment by suka233** [comment]
> 那可以增加自定义导图结构的功能吗
目前仅仅支持这些结构
![image](https://github.com/suka233/siyuan-kmind-plugin/assets/43712875/397692d9-f58f-4442-9b5e-1b821dbbd979)
