### ISSUE TITLE
希望能够支持公式（KaTex）

### ISSUE THREAD

**Issue by WingDr** [suka233/siyuan-kmind-plugin#3]
之前从一堆的思维导图跳到freeplane是因为能支持输入和渲染公式（虽然那边是latex代码都能渲染，但是我感觉没啥必要），如果思源里面的思维导图能支持就太好了。

我去查了一下KaTex直接就能从node库导入，具体链接在[这里](https://katex.org/docs/node)，相应的[API](https://katex.org/docs/api)看起来也比较简单。也不用做成markdown语法，直接和链接什么的插入和修改方法保持一致就行。

感谢大佬开发的挂件和插件！

**Comment by suka233** [comment]
渲染公式的话，一般的markdown编辑器应该可以搞定，比如思源开发者V姐开发的vditor。
之后的方向是研究一下目前富文本编辑采用的quill库是否能原生实现插入数学公式，如果不能，可能会提供一个选项，从富文本切换为markdown，编辑器采用vditor即可
但是目前开发重心不在此，可能需要一阵子之后才会上线此功能

**Comment by WingDr** [comment]
> 渲染公式的话，一般的markdown编辑器应该可以搞定，比如思源开发者V姐开发的vditor。 之后的方向是研究一下目前富文本编辑采用的quill库是否能原生实现插入数学公式，如果不能，可能会提供一个选项，从富文本切换为markdown，编辑器采用vditor即可 但是目前开发重心不在此，可能需要一阵子之后才会上线此功能

直接用vditor确实整体使用逻辑就比较统一了，狠狠地期待一下

**Comment by suka233** [comment]
> > 渲染公式的话，一般的markdown编辑器应该可以搞定，比如思源开发者V姐开发的vditor。 之后的方向是研究一下目前富文本编辑采用的quill库是否能原生实现插入数学公式，如果不能，可能会提供一个选项，从富文本切换为markdown，编辑器采用vditor即可 但是目前开发重心不在此，可能需要一阵子之后才会上线此功能
> 
> 直接用vditor确实整体使用逻辑就比较统一了，狠狠地期待一下

已经在现有的编辑器上支持了数学公式（katex）并且优化了一下编辑体验，自动获取焦点等等。但是坏消息是，插件版的kmind尚有缺陷，可能是多tab页的原因，导致拖拽节点调整节点的位置有几率会导致节点丢失，目前还没定位到具体原因。T.T   建议使用挂件版kmind，挂件版的数据是隔离的，所以无此bug
插件版已存在的数据可以无损导入挂件版

**Comment by suka233** [comment]
> > > 渲染公式的话，一般的markdown编辑器应该可以搞定，比如思源开发者V姐开发的vditor。 之后的方向是研究一下目前富文本编辑采用的quill库是否能原生实现插入数学公式，如果不能，可能会提供一个选项，从富文本切换为markdown，编辑器采用vditor即可 但是目前开发重心不在此，可能需要一阵子之后才会上线此功能
> > 
> > 
> > 直接用vditor确实整体使用逻辑就比较统一了，狠狠地期待一下
> 
> 已经在现有的编辑器上支持了数学公式（katex）并且优化了一下编辑体验，自动获取焦点等等。但是坏消息是，插件版的kmind尚有缺陷，可能是多tab页的原因，导致拖拽节点调整节点的位置有几率会导致节点丢失，目前还没定位到具体原因。T.T 建议使用挂件版kmind，挂件版的数据是隔离的，所以无此bug 插件版已存在的数据可以无损导入挂件版

节点丢失bug已经修复了，kmind插件满血复活啦

**Comment by WingDr** [comment]
> 节点丢失bug已经修复了，kmind插件满血复活啦

好耶！开发辛苦啦！
