### ISSUE TITLE
主题切换不起作用

### ISSUE THREAD

**Issue by xuw2024** [suka233/siyuan-kmind-plugin#30]
我是刚装的插件和挂件 2024/5/20
点了主题切换，没有任何作用
![image](https://github.com/suka233/siyuan-kmind-plugin/assets/169825183/e9ab43f7-49ed-404b-8c41-cdeca98f0c71)

**Comment by a877429929** [comment]
确实，我也遇到了，刚准备过来提个issue

**Comment by suka233** [comment]
新版本有点问题，回滚到上个版本或者等等下个版本修复
