### ISSUE TITLE
移动到新窗口后，不能正常显示

### ISSUE THREAD

**Issue by pisceswb** [suka233/siyuan-kmind-plugin#32]
如题，望修复，谢谢！

**Comment by suka233** [comment]
请截图说明一下复现的步骤

**Comment by pisceswb** [comment]
https://github.com/suka233/siyuan-kmind-plugin/assets/104658457/be2c35ba-9b20-4b36-895c-cff60261b2df

**Comment by suka233** [comment]
> -.QQ1783420665-.Mcc-2024-05-25-07-29-34.MP4

收到  多谢反馈

**Comment by hassan5134** [comment]
同样的问题，望修复，谢谢

**Comment by suka233** [comment]
请更新最新版本，在思源文档树新建的KMind可以打开新窗口了

**Comment by hassan5134** [comment]
> 请更新最新版本，在思源文档树新建的KMind可以打开新窗口了

插件版本：  v2.6.0
![image](https://github.com/user-attachments/assets/6ecc0109-5bf4-44fc-8e3f-991889b76fd1)
思源版本： v3.1.13
系统：Linux

还是不行呢 😅
