### ISSUE TITLE
【咨询】移动端是否可以使用？

### ISSUE THREAD

**Issue by chliuqi** [suka233/siyuan-kmind-plugin#33]
在PC端编辑保存后，在移动端打开显示：未找到ID为[/kmind-plugin?data=............]的内容块 v3.0.16
我想知道现在移动端是否可以使用？谢谢。

**Comment by suka233** [comment]
以前没有出现过这种情况，移动端可以使用，这种情况可能是没有同步完毕就打开了导图，你可以再同步试试，在PC端完全同步后，然后移动端先同步完毕后，再打开导图；
然后移动端建议只查看不编辑，因为交互做的很烂

**Comment by chliuqi** [comment]
好的，感谢回答
