### ISSUE TITLE
导入的xmind文件，会丢失图片;

### ISSUE THREAD

**Issue by nianlifeixing** [suka233/siyuan-kmind-plugin#37]
导入xmind文件后，里边的图片的节点会丢失；
能否做到像xmind一样，直接粘贴一个图片进去了，而不是选择图片的本地地址

**Comment by suka233** [comment]
1.导入功能只提供有限的支持。。
2.当前是支持直接粘贴图片的，具体步骤是：点击要粘贴图片的节点，然后ctrl+v粘贴即可
![recording](https://github.com/suka233/siyuan-kmind-plugin/assets/43712875/9e908d0b-522b-4b8b-bae1-a92c18db0ed8)
