### ISSUE TITLE
希望添加创建文件夹的能力。

### ISSUE THREAD

**Issue by bintong-github** [suka233/siyuan-kmind-plugin#38]
能否让kmind支持创建文件夹，现在每个文件都是独立的存在，新建只能新建思维导图，而不能建文件夹。支持新建文件夹这样文件会更加有序。产品非常棒，感谢大佬。

**Comment by gaoxingxs** [comment]
希望能够床创建文件夹、自定义排序，感谢大佬。

**Comment by pisceswb** [comment]
产品非常棒，感谢大佬。
同样希望添加文件夹功能

**Comment by suka233** [comment]
请更新最新版本，已经可以在思源文档树新建KMind了
