### ISSUE TITLE
版本都更新到最新了，主题基本全部失效，只有2个有点反应

### ISSUE THREAD

**Issue by XTTGO** [suka233/siyuan-kmind-plugin#39]
![20240630_113853](https://github.com/suka233/siyuan-kmind-plugin/assets/38094114/f53f5864-99d9-48ed-b56f-27df163b1be1)

录制了个视频，看看效果，背景颜色，节点样式基本没有改变

https://github.com/suka233/siyuan-kmind-plugin/assets/38094114/95936185-c4d6-4fe9-8b03-9d8d3685c79f

**Comment by suka233** [comment]
新版本确实有bug，要不回滚到上个版本，要不等等我更新下一个修复版

**Comment by XTTGO** [comment]
> 新版本确实有bug，要不回滚到上个版本，要不等等我更新下一个修复版

嗯呢，小弟就是及时的反应下遇到的情况，静等您的更新，辛苦大佬啦~  给大佬端茶

**Comment by suka233** [comment]
新版已修复
https://github.com/suka233/siyuan-kmind-plugin/releases/tag/v2.0.0-beta.1
