### ISSUE TITLE
希望节点的编辑框能够明显一些，另外是否可以设置最低高度？

### ISSUE THREAD

**Issue by WingDr** [suka233/siyuan-kmind-plugin#4]
目前的编辑框是纯白的，一方面是没有内容的区域没办法聚焦插入光标，另一方面视觉观感上也不好

![image](https://github.com/suka233/siyuan-kmind-plugin/assets/63407442/486d5e52-d7a5-42ee-a76e-ee4a4a9dfda2)

看了一下dom，不知道能不能设置设个container的样式，我看这个的大小跟我上面画的一模一样，editor本身好像就那么一条，但是其实也没啥关系，大不了就点不进去，container这里背景色设置的稍微深一些就好。如果editor的最低高度能和container一样（点击下方会自动把光标放到最后）就更好了

![image](https://github.com/suka233/siyuan-kmind-plugin/assets/63407442/07115668-a098-4d24-8087-1cf4cccc312a)

**Comment by suka233** [comment]
感谢建议，这里是因为富文本编辑使用的是quill库，quill库的编辑功能是把div的contenteditable设为true实现的。所以编辑框只有一行。
并且quill库比较老了，我也不太熟悉quill，之后会尽力尝试优化一下

**Comment by WingDr** [comment]
> 感谢建议，这里是因为富文本编辑使用的是quill库，quill库的编辑功能是把div的contenteditable设为true实现的。所以编辑框只有一行。 并且quill库比较老了，我也不太熟悉quill，之后会尽力尝试优化一下

看了一下文档，这里确实不好搞，实在不行就算了
