### ISSUE TITLE
关于在文档中嵌入、引入kmind插件功能

### ISSUE THREAD

**Issue by bin38121cn** [suka233/siyuan-kmind-plugin#40]
目前已知，kmind可以复制链接，然后点击跳转。kmind插件确实比较好的分离了文档和导图，但是如果想要在文档中直接嵌入预览kmind，好像无法做到。
<img width="926" alt="image" src="https://github.com/user-attachments/assets/960fa3e2-0f45-4568-931b-747c7c5e3b7e">
而只能通过挂件形式导入，比较麻烦
<img width="1245" alt="image" src="https://github.com/user-attachments/assets/f0b694bc-b13b-4441-b5c6-420ccfc2a835">
对比obsidian中，在文档中引入excaildraw又或者canvas的方式
<img width="958" alt="image" src="https://github.com/user-attachments/assets/83f34cd3-c0f7-4937-8305-17ce2aa372f9">

**Comment by MXDMM** [comment]
+1,如果这个功能实现了，那么完全实现了文字与导图相结合了。
插件功能与思源相结合，完全超越了xmind这些专用工具，1+1远远大于2。

**Comment by xiaofeng010766** [comment]
+1

**Comment by houzy** [comment]
支持，太需要这个了，否则和思源笔记比较割裂

**Comment by hassan5134** [comment]
+1

**Comment by suka233** [comment]
新版已经加上镜像块功能
