### ISSUE TITLE
在最新版的 Siyuan 笔记中，二级节点开始中文显示乱码

### ISSUE THREAD

**Issue by iyuge2** [suka233/siyuan-kmind-plugin#41]
<img width="407" alt="image" src="https://github.com/user-attachments/assets/51aea574-77d5-4a22-8a95-6b7dfb223a3d">

插件版本号：v2.0.0-beta.1
思源笔记版本：v3.1.3

**Comment by suka233** [comment]
所有的导图都是这样了吗？目前我这里无法复现，可以的话，导出kmind源文件传上来看看呢。
建议新建一个空白的思源工作空间，只开kmind插件试试，排除一下其它插件和主题的影响。

**Comment by suka233** [comment]
你好 由于无法复现 所以如果有更新的情况请重新打开此issue
