### ISSUE TITLE
希望在文档编辑页面插入kmind挂件时，自动缩放居中显示预览画面，而不是编辑页面

### ISSUE THREAD

**Issue by Yohmien** [suka233/siyuan-kmind-plugin#43]
存在问题：
+ 挂件显示编辑页面，在文档查看时并不美观，而且存在误操作可能，建议只在插件页面编辑时显示编辑页面，文档阅读显示预览页面
+ 挂件无法实现自动居中全内容显示，可参考excalidraw挂件显示效果

**Comment by suka233** [comment]
现在挂件已经默认隐藏编辑框了，请更新最新版本试试

**Comment by yumuing** [comment]
![image](https://github.com/user-attachments/assets/fc78a58f-304e-4156-9315-375c69d228bb)
红色边框部分能否实现，鼠标悬停到该位置自动显示，其他时间自动隐藏，展示时会更加美观，因为在预览窗口，大部分功能无用，也就没必要显示出来了，感谢开发者
