### ISSUE TITLE
讨论下鼠标左键与中键

### ISSUE THREAD

**Issue by lijiayin110** [suka233/siyuan-kmind-plugin#48]
需求描述：希望能新增框选节点的能力

需求背景：
我用的几个竞品思维导图工具，鼠标左键都是支持框选节点的，咱们产品只能通过ctrl进行多选，当需要多选的节点较多时，无法批量选取。另外，目前鼠标左键与中键都是平移画布，是否保留中键平移画布即可，鼠标左键可以支持框选。

**Comment by suka233** [comment]
更新到最新版本，已经支持鼠标拖拽全局配置
