### ISSUE TITLE
Docker网页如何使用免费版

### ISSUE THREAD

**Issue by HotAntOne** [suka233/siyuan-kmind-plugin#49]
背景：Docker安装，思源笔记和kmind均为当前最新版本。
问题：按照教程创建kmind，显示需要启用pro后才能使用。如何正确使用免费版？
![image](https://github.com/user-attachments/assets/a793ce49-b0a3-4afb-8d0c-8950898ff060)
![image](https://github.com/user-attachments/assets/4e43b2cb-8d8d-4ea4-8972-64d28db2bc32)

**Comment by suka233** [comment]
你好  挂件和 dock栏创建导图都是免费的
![image](https://github.com/user-attachments/assets/b9a31639-e7c1-4f87-b352-e340f2bde694)
