### ISSUE TITLE
docker版浏览器无法打开超链接

### ISSUE THREAD

**Issue by 3417157769** [suka233/siyuan-kmind-plugin#5]
![image](https://github.com/suka233/siyuan-kmind-plugin/assets/100463912/b350b964-b3fe-4fdf-8641-ea1ac95baa4c)
使用云服务器部署的思源笔记，在任何浏览器点击添加好的链接都这样，也试了alt+点击，也不行，不是用的客户端。

**Comment by 3417157769** [comment]
![image](https://github.com/suka233/siyuan-kmind-plugin/assets/100463912/70411374-2236-41db-b386-e40280f63a5e)

**Comment by suka233** [comment]
siyuan://开头的协议是思源客户端注册到系统中的，意味着这是个系统级的功能，脱离客户端就无法注册了，所以这是个正常的状况。
但是也并非无解，后面我会试着研究下，拦截导图中siyuan开头的超链接，跳转到指定块，但是这需要思源的api支持，不一定能很快上线

**Comment by 3417157769** [comment]
哦哦，我直接用电脑客户端了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月12日(星期六) 凌晨1:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [suka233/siyuan-kmind-plugin] docker版浏览器无法打开超链接 (Issue #5)





 
siyuan://开头的协议是思源客户端注册到系统中的，意味着这是个系统级的功能，脱离客户端就无法注册了，所以这是个正常的状况。
 但是也并非无解，后面我会试着研究下，拦截导图中siyuan开头的超链接，跳转到指定块，但是这需要思源的api支持，不一定能很快上线
