### ISSUE TITLE
思源快捷键不能在 kmind插件里使用

### ISSUE THREAD

**Issue by 599809952** [suka233/siyuan-kmind-plugin#54]
我在思源设置的全屏快捷键 F1，在kmind里编辑完成后 再按F1就切不回来了，F2重命名快捷键kmind插件也不能用

**Comment by suka233** [comment]
kmind的快捷键和思源的快捷键不通用，退出全屏点击esc试试。重命名的话现在新加了新建的时候可以设置文档名的功能，可以试试
