### ISSUE TITLE
kmind插件无法渲染，重启后丢失数据

### ISSUE THREAD

**Issue by chenspnjupt** [suka233/siyuan-kmind-plugin#55]

**Comment by suka233** [comment]
你好，
1.需要确认下是哪个位置的导图丢失了，目前有三种kmind导图，一是文档树导图，二是挂件，三是左下角dock栏的导图；
2.如果确认发生丢失，可以通过如下操作回滚一下，注意复制一个当前的新的工作空间，在复制出来的工作空间操作回滚：
![image](https://github.com/user-attachments/assets/cad3db85-109a-4cc8-9aad-84213d26d81c)
3.请顺便回忆一下做了什么特别的操作；
4.最近会加上单个导图的历史记录回退功能，到时候会提供更多的数据保障；

**Comment by suka233** [comment]
新版本新增了异常空数据拦截功能和历史版本，请更新到最新版
