### ISSUE TITLE
鸿蒙5.0xmind导入流程优化

### ISSUE THREAD

**Issue by Suheisdead** [suka233/siyuan-kmind-plugin#59]
目前5.0系统可行的导入流程是先将xmind文件下载到文件管理器，后打开kmind新建导图-导入-文件管理器选择文件，流程较为繁琐。但我注意到xmind支持直接通过系统分享-导入应用，但能识别的可导入应用中无思源笔记。

**Comment by suka233** [comment]
系统级别的文档导入是思源本体的行为，插件暂时没法干预
