### ISSUE TITLE
火狐浏览器打开文字显示不出来，换谷歌浏览器能正常使用

### ISSUE THREAD

**Issue by HeRenChuJianYue** [suka233/siyuan-kmind-plugin#6]
![image](https://github.com/suka233/siyuan-kmind-plugin/assets/97729613/41e22073-7556-4947-bf20-dc4b6e8974c9)
火狐浏览器无法显示字体，只有选中之后，才能看到框里写的文字。
![image](https://github.com/suka233/siyuan-kmind-plugin/assets/97729613/5ae708bb-3821-4dab-aaae-ffcf39778337)
换个谷歌浏览器能正常访问，建议适配一下火狐浏览器。

**Comment by suka233** [comment]
这个得找找解决方案。。。建议目前还是主要用chrome内核的浏览器吧.
关联一下上游库的[#issue272](https://github.com/wanglin2/mind-map/issues/272)

**Comment by suka233** [comment]
可以更新插件和挂件到最新版再试试
