### ISSUE TITLE
在中心主题节点上按下Ctrl+V后再按Tab键会导致节点消失不见

### ISSUE THREAD

**Issue by yongnianliu** [suka233/siyuan-kmind-plugin#7]
环境:
操作系统:Win11 x64 专业版
思源版本:v2.9.9
kmind插件版本:v1.1.2

复现步骤:
1.新建脑图
2.选中主题节点"suka"
3.按下组合键 Ctrl+V
4.按下Tab键
主题节点"suka"节点消失且操作无法撤销

建议:
xmind在节点上Ctrl+V行为是以粘贴板内容创建一个子节点，挺好用的，期待支持

**Comment by suka233** [comment]
感谢反馈，复现了一下，确实有这个bug。

下个版本会加入直接ctrl+V以粘贴板内容新建一个子节点的功能，应该就可以直接修复这个bug

**Comment by suka233** [comment]
hello ，复制粘贴已经修复，并新增了其它功能，请更新kmind插件到最新版，并且kmind**挂件**到v1.2.0版本之后，即可体验
