### ISSUE TITLE
新建文件后，无法显示任何数据

### ISSUE THREAD

**Issue by bin38121cn** [suka233/siyuan-kmind-plugin#8]
![image](https://github.com/suka233/siyuan-kmind-plugin/assets/10770216/1487cbda-3ce1-421f-bc11-99d8b55225ce)

不知道什么原因？从旧版本更新到最新版本后，新建文件就变成这样子

**Comment by bin38121cn** [comment]
噢，我知道了，我刚把挂件里的删除了，插件的就无法显示，必须挂件和插件同时存在才行

**Comment by suka233** [comment]
是的，插件复用了挂件的代码，而挂件的悬浮预览功能又会使用到插件提供的能力，所以目前来说，插件和挂件是一起配合使用最好
