### ISSUE TITLE
插件版的kmind能在某篇文章里插入么？

### ISSUE THREAD

**Issue by bin38121cn** [suka233/siyuan-kmind-plugin#9]
之前挂件版本的kmind可以在文章直接插入。
后面作者为了挂件复用性，开发出插件版。
但是有时候在插件版里写完了，还是想插回到文章里，能不能做到只要修改插件版的kmind，所有与之关联的文章，都会作出对应修改

**Comment by suka233** [comment]
你好，目前暂不支持。
可以采用如下步骤间接完成，缺点是不能实时更新
1.插件新建的一张导图：A
2.要插入的文章中插入一个新的kmind挂件
3.在挂件中使用导入的功能导入A即可

注意：插件版的导图源文件在 你的工作空间目录\data\storage\petal\kmind\ 目录下
所以以上的A的源文件即为 你的工作空间目录\data\storage\petal\kmind\A.kmind
